import type { Job } from "@/lib/actions/jobs"

export const sampleJobs: Job[] = [
  {
    id: "1",
    title: "Senior Frontend Developer",
    company: "TechCorp Inc.",
    location: "San Francisco, CA",
    type: "Full-time",
    salary: "$120,000 – $150,000",
    description:
      "We are looking for a Senior Frontend Developer to join our dynamic team. You will be responsible for developing user-facing web applications using modern JavaScript frameworks like React and Next.js.",
    requirements: [
      "5+ years of React experience",
      "TypeScript proficiency",
      "Experience with Next.js",
      "Strong CSS skills",
    ],
    benefits: ["Health insurance", "Dental coverage", "401k matching", "Flexible work hours", "Remote work options"],
    posted_date: "2024-02-01",
    application_deadline: "2024-02-15",
    contact_email: "careers@techcorp.com",
  },
  {
    id: "2",
    title: "UX/UI Designer",
    company: "Design Studio Pro",
    location: "New York, NY",
    type: "Full-time",
    salary: "$80,000 – $100,000",
    description:
      "Join our creative team as a UX/UI Designer. You will work on exciting projects for various clients, creating intuitive and beautiful user experiences.",
    requirements: [
      "3+ years of UX/UI design experience",
      "Proficiency in Figma & Adobe Creative Suite",
      "Strong portfolio",
      "User-centred design principles",
    ],
    benefits: ["Creative environment", "Professional development budget", "Health insurance", "Flexible PTO"],
    posted_date: "2024-02-03",
    application_deadline: "2024-02-10",
    contact_email: "jobs@designstudiopro.com",
  },
  {
    id: "3",
    title: "Backend Engineer",
    company: "DataFlow Systems",
    location: "Austin, TX",
    type: "Full-time",
    salary: "$100,000 – $130,000",
    description:
      "We need a skilled Backend Engineer to help build and maintain our data processing systems. You will work with large-scale distributed systems and modern cloud technologies.",
    requirements: [
      "4+ years of backend development",
      "Experience with Node.js or Python",
      "Database design skills",
      "Cloud platform experience (AWS/GCP)",
    ],
    benefits: ["Stock options", "Health insurance", "Learning stipend", "Gym membership"],
    posted_date: "2024-02-05",
    application_deadline: "2024-02-12",
    contact_email: "hiring@dataflowsystems.com",
  },
  {
    id: "4",
    title: "DevOps Engineer",
    company: "CloudTech Solutions",
    location: "Seattle, WA",
    type: "Full-time",
    salary: "$110,000 – $140,000",
    description:
      "Looking for a DevOps Engineer to help automate and streamline our operations and processes. You'll work with cutting-edge cloud technologies and CI/CD pipelines.",
    requirements: [
      "3+ years of DevOps experience",
      "Experience with AWS/Azure/GCP",
      "Docker and Kubernetes knowledge",
      "Infrastructure as Code (Terraform/CloudFormation)",
    ],
    benefits: ["Remote work", "Health insurance", "Stock options", "Professional development"],
    posted_date: "2024-02-07",
    application_deadline: "2024-02-20",
    contact_email: "devops@cloudtech.com",
  },
  {
    id: "5",
    title: "Product Manager",
    company: "InnovateCorp",
    location: "Boston, MA",
    type: "Full-time",
    salary: "$130,000 – $160,000",
    description:
      "We're seeking a Product Manager to drive product strategy and execution. You'll work closely with engineering, design, and business teams to deliver exceptional products.",
    requirements: [
      "5+ years of product management experience",
      "Experience with agile methodologies",
      "Strong analytical skills",
      "Excellent communication skills",
    ],
    benefits: ["Equity package", "Health insurance", "Flexible schedule", "Learning budget"],
    posted_date: "2024-02-08",
    application_deadline: "2024-02-25",
    contact_email: "pm@innovatecorp.com",
  },
  {
    id: "6",
    title: "Data Scientist",
    company: "Analytics Pro",
    location: "Chicago, IL",
    type: "Full-time",
    salary: "$95,000 – $125,000",
    description:
      "Join our data science team to extract insights from large datasets and build predictive models. You'll work on exciting projects across various industries.",
    requirements: [
      "3+ years of data science experience",
      "Python/R proficiency",
      "Machine learning expertise",
      "SQL and database knowledge",
    ],
    benefits: ["Remote work options", "Health insurance", "Conference budget", "Flexible hours"],
    posted_date: "2024-02-10",
    application_deadline: "2024-02-28",
    contact_email: "data@analyticspro.com",
  },
  {
    id: "7",
    title: "Mobile Developer (iOS)",
    company: "AppCraft Studios",
    location: "Los Angeles, CA",
    type: "Full-time",
    salary: "$105,000 – $135,000",
    description:
      "We're looking for an iOS developer to create amazing mobile experiences. You'll work on consumer-facing apps with millions of users.",
    requirements: [
      "4+ years of iOS development",
      "Swift and Objective-C proficiency",
      "App Store publishing experience",
      "UI/UX design understanding",
    ],
    benefits: ["Stock options", "Health insurance", "Gym membership", "Catered meals"],
    posted_date: "2024-02-12",
    application_deadline: "2024-03-01",
    contact_email: "ios@appcraft.com",
  },
  {
    id: "8",
    title: "Cybersecurity Analyst",
    company: "SecureNet Inc.",
    location: "Washington, DC",
    type: "Full-time",
    salary: "$85,000 – $115,000",
    description:
      "Join our cybersecurity team to protect our organization from digital threats. You'll monitor security systems and respond to incidents.",
    requirements: [
      "2+ years of cybersecurity experience",
      "Security certifications (CISSP, CEH, etc.)",
      "Network security knowledge",
      "Incident response experience",
    ],
    benefits: ["Security clearance bonus", "Health insurance", "Training budget", "Flexible work"],
    posted_date: "2024-02-14",
    application_deadline: "2024-03-05",
    contact_email: "security@securenet.com",
  },
  {
    id: "9",
    title: "Marketing Manager",
    company: "GrowthCo",
    location: "Miami, FL",
    type: "Full-time",
    salary: "$75,000 – $95,000",
    description:
      "Lead our marketing efforts to drive brand awareness and customer acquisition. You'll manage campaigns across multiple channels.",
    requirements: [
      "3+ years of marketing experience",
      "Digital marketing expertise",
      "Analytics and data-driven approach",
      "Content creation skills",
    ],
    benefits: ["Performance bonuses", "Health insurance", "Creative freedom", "Team events"],
    posted_date: "2024-02-16",
    application_deadline: "2024-03-10",
    contact_email: "marketing@growthco.com",
  },
  {
    id: "10",
    title: "Sales Representative",
    company: "SalesForce Pro",
    location: "Denver, CO",
    type: "Full-time",
    salary: "$60,000 – $80,000 + Commission",
    description:
      "Join our sales team to drive revenue growth. You'll work with enterprise clients to understand their needs and provide solutions.",
    requirements: [
      "2+ years of B2B sales experience",
      "CRM software proficiency",
      "Excellent communication skills",
      "Goal-oriented mindset",
    ],
    benefits: ["Commission structure", "Health insurance", "Car allowance", "Sales incentives"],
    posted_date: "2024-02-18",
    application_deadline: "2024-03-15",
    contact_email: "sales@salesforcepro.com",
  },
  {
    id: "11",
    title: "Quality Assurance Engineer",
    company: "TestTech Solutions",
    location: "Portland, OR",
    type: "Full-time",
    salary: "$70,000 – $90,000",
    description:
      "Ensure the quality of our software products through comprehensive testing. You'll work with development teams to identify and resolve issues.",
    requirements: [
      "3+ years of QA experience",
      "Test automation tools knowledge",
      "Bug tracking systems experience",
      "Attention to detail",
    ],
    benefits: ["Remote work", "Health insurance", "Professional development", "Flexible schedule"],
    posted_date: "2024-02-20",
    application_deadline: "2024-03-20",
    contact_email: "qa@testtech.com",
  },
  {
    id: "12",
    title: "Content Writer",
    company: "ContentCraft Agency",
    location: "Remote",
    type: "Full-time",
    salary: "$50,000 – $70,000",
    description:
      "Create engaging content for various clients across different industries. You'll write blog posts, articles, and marketing copy.",
    requirements: [
      "2+ years of content writing experience",
      "SEO knowledge",
      "Research skills",
      "Adaptable writing style",
    ],
    benefits: ["Fully remote", "Health insurance", "Flexible hours", "Writing tools budget"],
    posted_date: "2024-02-22",
    application_deadline: "2024-03-25",
    contact_email: "content@contentcraft.com",
  },
  {
    id: "13",
    title: "Machine Learning Engineer",
    company: "AI Innovations",
    location: "San Jose, CA",
    type: "Full-time",
    salary: "$140,000 – $180,000",
    description:
      "Build and deploy machine learning models at scale. You'll work on cutting-edge AI projects and research.",
    requirements: [
      "4+ years of ML engineering experience",
      "Python and TensorFlow/PyTorch",
      "Cloud platforms experience",
      "PhD in related field preferred",
    ],
    benefits: ["Stock options", "Health insurance", "Research budget", "Conference attendance"],
    posted_date: "2024-02-24",
    application_deadline: "2024-03-30",
    contact_email: "ml@aiinnovations.com",
  },
  {
    id: "14",
    title: "HR Generalist",
    company: "PeopleFirst Corp",
    location: "Atlanta, GA",
    type: "Full-time",
    salary: "$55,000 – $75,000",
    description:
      "Support all aspects of human resources including recruitment, employee relations, and policy development.",
    requirements: [
      "3+ years of HR experience",
      "SHRM certification preferred",
      "Employment law knowledge",
      "Strong interpersonal skills",
    ],
    benefits: ["Health insurance", "Retirement plan", "Professional development", "Work-life balance"],
    posted_date: "2024-02-26",
    application_deadline: "2024-04-01",
    contact_email: "hr@peoplefirst.com",
  },
  {
    id: "15",
    title: "Financial Analyst",
    company: "FinanceHub",
    location: "New York, NY",
    type: "Full-time",
    salary: "$80,000 – $100,000",
    description:
      "Analyze financial data and create reports to support business decisions. You'll work with various departments to provide insights.",
    requirements: [
      "2+ years of financial analysis experience",
      "Excel and financial modeling skills",
      "CFA or similar certification preferred",
      "Strong analytical skills",
    ],
    benefits: ["Bonus structure", "Health insurance", "Professional development", "Downtown location"],
    posted_date: "2024-02-28",
    application_deadline: "2024-04-05",
    contact_email: "finance@financehub.com",
  },
  {
    id: "16",
    title: "Graphic Designer",
    company: "Creative Minds Studio",
    location: "Phoenix, AZ",
    type: "Part-time",
    salary: "$25 – $35 per hour",
    description:
      "Create visual designs for various marketing materials and digital platforms. You'll work on diverse projects for multiple clients.",
    requirements: [
      "2+ years of graphic design experience",
      "Adobe Creative Suite proficiency",
      "Strong portfolio",
      "Brand design experience",
    ],
    benefits: ["Flexible schedule", "Creative environment", "Portfolio building", "Remote options"],
    posted_date: "2024-03-01",
    application_deadline: "2024-04-10",
    contact_email: "design@creativeminds.com",
  },
  {
    id: "17",
    title: "Network Administrator",
    company: "NetWork Solutions",
    location: "Dallas, TX",
    type: "Full-time",
    salary: "$65,000 – $85,000",
    description:
      "Maintain and troubleshoot network infrastructure. You'll ensure optimal network performance and security.",
    requirements: [
      "3+ years of network administration",
      "Cisco certifications preferred",
      "Network security knowledge",
      "Troubleshooting skills",
    ],
    benefits: ["Health insurance", "Certification reimbursement", "On-call compensation", "Technical training"],
    posted_date: "2024-03-03",
    application_deadline: "2024-04-15",
    contact_email: "network@networksolutions.com",
  },
  {
    id: "18",
    title: "Business Analyst",
    company: "Strategy Consultants",
    location: "Minneapolis, MN",
    type: "Full-time",
    salary: "$75,000 – $95,000",
    description:
      "Analyze business processes and recommend improvements. You'll work with stakeholders to gather requirements and implement solutions.",
    requirements: [
      "3+ years of business analysis experience",
      "Process improvement knowledge",
      "Stakeholder management skills",
      "Documentation skills",
    ],
    benefits: ["Health insurance", "Professional development", "Flexible work", "Bonus opportunities"],
    posted_date: "2024-03-05",
    application_deadline: "2024-04-20",
    contact_email: "ba@strategyconsultants.com",
  },
  {
    id: "19",
    title: "Customer Success Manager",
    company: "ClientCare Inc.",
    location: "Nashville, TN",
    type: "Full-time",
    salary: "$70,000 – $90,000",
    description:
      "Ensure customer satisfaction and drive retention. You'll work closely with clients to maximize their success with our platform.",
    requirements: [
      "2+ years of customer success experience",
      "SaaS platform experience",
      "Excellent communication skills",
      "Problem-solving abilities",
    ],
    benefits: ["Health insurance", "Customer success tools", "Team building events", "Growth opportunities"],
    posted_date: "2024-03-07",
    application_deadline: "2024-04-25",
    contact_email: "success@clientcare.com",
  },
  {
    id: "20",
    title: "Software Architect",
    company: "ArchTech Systems",
    location: "San Francisco, CA",
    type: "Full-time",
    salary: "$160,000 – $200,000",
    description:
      "Design and oversee the implementation of complex software systems. You'll provide technical leadership and architectural guidance.",
    requirements: [
      "8+ years of software development experience",
      "System design expertise",
      "Leadership experience",
      "Multiple programming languages",
    ],
    benefits: ["Stock options", "Health insurance", "Technical conferences", "Sabbatical program"],
    posted_date: "2024-03-09",
    application_deadline: "2024-04-30",
    contact_email: "architect@archtech.com",
  },
  {
    id: "21",
    title: "Digital Marketing Specialist",
    company: "MarketBoost Agency",
    location: "Remote",
    type: "Contract",
    salary: "$40 – $60 per hour",
    description:
      "Execute digital marketing campaigns across various channels. You'll manage social media, email marketing, and paid advertising.",
    requirements: [
      "2+ years of digital marketing experience",
      "Social media platform expertise",
      "Google Ads certification",
      "Analytics tools proficiency",
    ],
    benefits: ["Fully remote", "Flexible hours", "Performance bonuses", "Marketing tools access"],
    posted_date: "2024-03-11",
    application_deadline: "2024-05-01",
    contact_email: "digital@marketboost.com",
  },
]
